travis:
  secure:
    BINSTAR_TOKEN: VE+hINMea88Blj5bs3nvoueGSFbFiSZIh127L534RKvC8m6wE/v+C12H0bizS9M/lxL+z4Bh150RNRtET8ZH75g+a/fgkTXlu4eUTn9aS1ztAGzkBiMEqeLY1zW8l6cgfppIxPA82xhMqa3cpvgsJaWNmMMfY1aB4vCXJDHMKwW2uE047Mcgzvl8JHoovwQwsXqkJUraRT6dyB3w1NXxu0CuP7Poy5+8eRdUFU9+ODLQ9BgjNf/5pRCHgiDkYFqs6Ey3yrfa1cr5PoNOxUjtwjDv/DcYQw2xSzESIH44aS3afoL3SMOa+4WGSTI+Mx5zgKPT+nuVXmy9pMkNVev18BOWY8HZw28WB+OQA9WV1IZYRRgWbIIp0Iaifsw7PD5lENlEFwkdbPp2lxIcgnNIyqAKOwRvze6S5wWnDHFcfi/s8LlLysSkAzbAdQlxmtaLuhxxMeQbjQ5IfSIFhPi58Qfqr3oXOO9reqRa9K3JRrWK6u5QQiaSD8PmQLzc+920B39SiHa4UH6+D1aEKUswf+kWMut43wNoL/dhy8HjfjNWLItDSAFBzq7cMPv61V0bF1D8eGEoaDkcQ30VkjWufEZQEM6fzpJbX/dTpFG8lLdK/CVtQmYWsOShdPY9VMBTwERL0R2dhprwNc/+XMwC+5oaQYCX6mgDRYnPzvKrQew=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
